package com.codesimple.bookstore.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
//@Table(name = "Books")   //table name diff irundha idha use pannanum
public class Book {
	@Id    //primary key nu annotate panradhuku
	@GeneratedValue(strategy = GenerationType.IDENTITY)   //its autogenerated value so this anotation
	private Long id;
	private String name;
	
	@Column(name = "descr")
	private String desc;
	private Integer yearOfPublication;
	private String bookType;
	
	
	public Book() {
		super();
	}
	public Book(Long id, String name, String desc, Integer yearOfPublication, String bookType) {
		super();
		this.id = id;
		this.name = name;
		this.desc = desc;
		this.yearOfPublication = yearOfPublication;
		this.bookType = bookType;
	}
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getDesc() {
		return desc;
	}
	public void setDesc(String desc) {
		this.desc = desc;
	}
	public Integer getYearOfPublication() {
		return yearOfPublication;
	}
	public void setYearOfPublication(Integer yearOfPublication) {
		this.yearOfPublication = yearOfPublication;
	}
	public String getBookType() {
		return bookType;
	}
	public void setBookType(String bookType) {
		this.bookType = bookType;
	}
	
	
	

}